package workers

const (
	qFetchUncheckedSubmissions = `
		SELECT ID, STATUS_ID, SOLUTION
		FROM SUBMISSION
		WHERE STATUS_ID = 1
    `
	qFetchSubmissionRestrictions = `
		SELECT RT.NAME AS RESTRICTION_TYPE, R.DEFINITION
		FROM SUBMISSION S
		JOIN PROBLEM P ON S.PROBLEM_ID = P.ID
		JOIN PROBLEM_RESTRICTION PR on P.ID = PR.PROBLEM_ID
		JOIN RESTRICTION R on PR.RESTRICTION_ID = R.ID
		JOIN RESTRICTION_TYPE RT on R.TYPE_ID = RT.ID
		WHERE S.ID = :1
    `
	qFetchSelectionInfo = `
		SELECT P.REFERENCE_SOLUTION, SS.NAME AS DEFAULT_SCHEMA, SP.CHECK_ORDER, SP.CHECK_COLUMN_NAMES
		FROM SUBMISSION S
		JOIN PROBLEM P on S.PROBLEM_ID = P.ID
		JOIN SELECTION_PROBLEM SP on P.ID = SP.PROBLEM_ID
		JOIN SELECTION_SCHEMA SS on SP.DEFAULT_SCHEMA_ID = SS.ID
		WHERE S.ID = :1
    `
	qFetchSelectionSchemas = `
		SELECT SS.NAME
		FROM SUBMISSION S
		JOIN PROBLEM P on S.PROBLEM_ID = P.ID
		JOIN SELECTION_PROBLEM_SCHEMA SPS on P.ID = SPS.PROBLEM_ID
		JOIN SELECTION_SCHEMA SS on SPS.SCHEMA_ID = SS.ID
		WHERE S.ID = :1
    `
	/*
		qCheckUnorderedContent = `
			WITH SOLUTION_RESULT AS (%[1]s), REFERENCE_RESULT AS (%[2]s)
			SELECT * FROM SOLUTION_RESULT
			MINUS
			SELECT * FROM REFERENCE_RESULT
			UNION ALL
			SELECT * FROM REFERENCE_RESULT
			MINUS
			SELECT * FROM SOLUTION_RESULT
		`
	*/
	qCheckUnorderedContent = `
		SELECT * FROM (%[1]s)
		MINUS
		SELECT * FROM (%[2]s)
		UNION ALL
		SELECT * FROM (%[2]s)
		MINUS
		SELECT * FROM (%[1]s)
	`
/*
	qCheckOrderedContent = `
		WITH SOLUTION_RESULT AS (%[1]s), REFERENCE_RESULT AS (%[2]s)
		SELECT SOLUTION_RESULT.*, ROWNUM FROM SOLUTION_RESULT
		MINUS
		SELECT REFERENCE_RESULT.*, ROWNUM FROM REFERENCE_RESULT
		UNION ALL
		SELECT REFERENCE_RESULT.*, ROWNUM FROM REFERENCE_RESULT
		MINUS
		SELECT SOLUTION_RESULT.*, ROWNUM FROM SOLUTION_RESULT
	`
*/
	qCheckOrderedContent = `
		SELECT SOLUTION_RESULT.*, ROWNUM FROM (%[1]s) SOLUTION_RESULT
		MINUS
		SELECT REFERENCE_RESULT.*, ROWNUM FROM (%[2]s) REFERENCE_RESULT
		UNION ALL
		SELECT REFERENCE_RESULT.*, ROWNUM FROM (%[2]s) REFERENCE_RESULT
		MINUS
		SELECT SOLUTION_RESULT.*, ROWNUM FROM (%[1]s) SOLUTION_RESULT
    `

	qUpdateSubmission = `
		UPDATE SUBMISSION
		SET STATUS_ID = :1, CHECKER_MESSAGE = :2 
		WHERE ID = :3
    `
)
